// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:646296019057:web:0a4bbec5e063e4e083fbd0',
    messagingSenderId: '646296019057',
    projectId: 'practice0-cb571',
    authDomain: 'practice0-cb571.firebaseapp.com',
    storageBucket: 'practice0-cb571.appspot.com',
    measurementId: 'G-1VF3W78L9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:646296019057:android:e9f4b0bea49f77c983fbd0',
    messagingSenderId: '646296019057',
    projectId: 'practice0-cb571',
    storageBucket: 'practice0-cb571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:646296019057:ios:c7638fd380c7941c83fbd0',
    messagingSenderId: '646296019057',
    projectId: 'practice0-cb571',
    storageBucket: 'practice0-cb571.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:646296019057:ios:c7638fd380c7941c83fbd0',
    messagingSenderId: '646296019057',
    projectId: 'practice0-cb571',
    storageBucket: 'practice0-cb571.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:646296019057:web:1f122665ead7ccda83fbd0',
    messagingSenderId: '646296019057',
    projectId: 'practice0-cb571',
    authDomain: 'practice0-cb571.firebaseapp.com',
    storageBucket: 'practice0-cb571.appspot.com',
    measurementId: 'G-7F2VZBF81X',
  );
}
